### ISSUE TITLE
AsyncTCP.h & DHT12.h libraries

### ISSUE THREAD

**Issue by erocm123** [Xinyuan-LilyGO/TTGO-HiGrow#1]
I have followed the instructions (including copying the libaries to the appropriate place) and I am getting complaints about AsyncTCP.h & DHT12.h. Where are the proper versions of these libraries?

TTGO-Multi-function-sensor-board:5:22: error: AsyncTCP.h: No such file or directory

**Comment by brunoslam** [comment]
I have the same issue with the DHT12.
Before upload the code i test the device and i can see the DHT humidity and temperature, but when i upload the sample code i can't get the values.
![Screenshot_1](https://user-images.githubusercontent.com/7435715/71198814-663bcd00-2273-11ea-92e2-e2ee731f626d.png)

**Comment by lewisxhe** [comment]
Sorry i forgot it, i already uploaded the used library @erocm123

**Comment by erocm123** [comment]
@lewisxhe , thank you. I will try it out.

**Comment by J4e8a16n** [comment]
The pins order on the probe is          
![images](https://user-images.githubusercontent.com/40242821/85921179-51ef1300-b848-11ea-87f8-2388f626838c.jpg)
![images](https://user-images.githubusercontent.com/40242821/85921181-587d8a80-b848-11ea-97e4-75026d66b602.jpg)

vcc-data-nc-ground.
What I see over the net for dht12 is  vcc-data-ground-nc

**Comment by lewisxhe** [comment]
dth12 It supports two protocols: single bus and I2C! @J4e8a16n
