### ISSUE TITLE
POWER_CTRL switches sensors?

### ISSUE THREAD

**Issue by miknuc** [Xinyuan-LilyGO/TTGO-HiGrow#6]
While implementing my own sketch for the hardware I wondered why all sensor readouts are null/blank/void..
Eventually I stumbled upon this line in the sketch:
`
    pinMode(POWER_CTRL, OUTPUT);
    digitalWrite(POWER_CTRL, 1);`

Is my assumption correct that pin 4 is used to switch the power supply for the sensors correct to safe power in deep sleep mode?

**Comment by lewisxhe** [comment]
Yes . It controls all sensor power
