### ISSUE TITLE
Wifi Connection Problem

### ISSUE THREAD

**Issue by endoramax** [Xinyuan-LilyGO/TTGO-HiGrow#8]
Hi, 

I use your ino file name is "TTGO-HiGrow". Also I have changed WIFI_SSID and WIFI_PASSWORD. I can't see any connection information and ip address in serial monitor. If I push boot button I can see smartconfig ................... endless. 

How can I connect my wifi and use this device ? 

Thank you.

**Comment by lewisxhe** [comment]
![1](https://user-images.githubusercontent.com/22990954/85006582-e2fd2480-b18c-11ea-945d-97b9fdd8602d.jpg)
![2](https://user-images.githubusercontent.com/22990954/85006609-eb555f80-b18c-11ea-80e3-145b445a346d.jpg)

**Comment by endoramax** [comment]
Thank you for your support. It works after applied your instruction.

**Comment by lewisxhe** [comment]
If you still have problems, please reopen.
